// Hand-authored color knowledge used to compose names and descriptive fields.

export type FamilyKey =
  | 'Red'
  | 'Orange'
  | 'Yellow'
  | 'Lime'
  | 'Green'
  | 'Olive'
  | 'Teal'
  | 'Cyan'
  | 'Blue'
  | 'Indigo'
  | 'Purple'
  | 'Magenta'
  | 'Pink'
  | 'Brown'
  | 'Beige'
  | 'Gray'
  | 'Black'
  | 'White';

export type Family = {
  noun: string;
  /** Hue range in OKLCH degrees used for undertones; null for neutrals. */
  range: [number, number] | null;
  undertones: [string, string];
  hueWords: string[];
  nameNouns: string[];
  imagery: string[];
  emotions: string[];
  personalities: string[];
  moods: string[];
  symbolism: string[];
  uses: string[];
  keywords: string[];
};

export const FAMILIES: Record<FamilyKey, Family> = {
  Red: {
    noun: 'red',
    range: [352, 40],
    undertones: ['a cool raspberry undertone', 'a warm orange undertone'],
    hueWords: [
      'Red',
      'Crimson',
      'Scarlet',
      'Ruby',
      'Carmine',
      'Cherry Red',
      'Garnet',
      'Cardinal Red',
    ],
    nameNouns: [
      'Ember',
      'Poppy',
      'Lantern',
      'Pomegranate',
      'Cinnabar',
      'Rosehip',
      'Flare',
      'Valentine',
      'Matador',
      'Hearth',
      'Paprika',
      'Chili',
      'Bloodstone',
      'Rouge',
      'Lacquer',
      'Beacon',
      'Tulip',
      'Salsa',
      'Kiln',
      'Sunfire',
    ],
    imagery: [
      'a ripe pomegranate',
      'glowing embers',
      "a cardinal's feathers",
      'red lacquerware',
      'a field of poppies',
      'polished garnet',
      'chili peppers drying in the sun',
      'a velvet theater curtain',
      'fresh cherries',
      'a paper festival lantern',
      "a fire engine's paint",
      'rosehips in autumn',
    ],
    emotions: [
      'Passionate',
      'Fiery',
      'Courageous',
      'Excited',
      'Romantic',
      'Urgent',
      'Determined',
      'Bold',
      'Intense',
      'Warm',
    ],
    personalities: [
      'Bold',
      'Assertive',
      'Confident',
      'Daring',
      'Passionate',
      'Spirited',
      'Driven',
      'Charismatic',
      'Fearless',
      'Decisive',
    ],
    moods: ['Energetic', 'Dramatic', 'Intense', 'Warm', 'Vibrant', 'Fiery', 'Festive', 'Charged'],
    symbolism: [
      'passion and desire',
      'courage and sacrifice',
      'luck and celebration',
      'love and devotion',
      'danger and urgency',
      'vitality and strength',
      'power and ambition',
      'fire and transformation',
    ],
    uses: [
      'sale and promotion banners',
      'call-to-action buttons',
      'restaurant and food branding',
      'sports team identities',
      'romantic campaigns',
      'error and alert states',
      'festive holiday packaging',
      'statement fashion pieces',
    ],
    keywords: [
      'Red',
      'Fiery',
      'Passion',
      'Warm',
      'Bold',
      'Romantic',
      'Energy',
      'Heat',
      'Love',
      'Courage',
    ],
  },
  Orange: {
    noun: 'orange',
    range: [40, 80],
    undertones: ['a reddish undertone', 'a golden undertone'],
    hueWords: [
      'Orange',
      'Tangerine',
      'Apricot',
      'Amber',
      'Saffron',
      'Persimmon',
      'Marigold',
      'Copper',
    ],
    nameNouns: [
      'Sunset',
      'Citrus',
      'Clementine',
      'Pumpkin',
      'Papaya',
      'Mango',
      'Campfire',
      'Monarch',
      'Harvest',
      'Bonfire',
      'Kumquat',
      'Fox',
      'Spice',
      'Canyon',
      'Lantern',
      'Nectar',
      'Ochre',
      'Tiger',
      'Desert',
      'Glow',
    ],
    imagery: [
      'a ripe tangerine',
      'a desert sunset',
      'autumn pumpkins',
      'monarch butterfly wings',
      'a crackling campfire',
      'sliced mango',
      'marigold garlands',
      'glowing copper pans',
      "a fox's coat",
      'saffron threads',
    ],
    emotions: [
      'Enthusiastic',
      'Cheerful',
      'Playful',
      'Optimistic',
      'Adventurous',
      'Warm',
      'Excited',
      'Friendly',
      'Lively',
      'Confident',
    ],
    personalities: [
      'Sociable',
      'Adventurous',
      'Creative',
      'Outgoing',
      'Spontaneous',
      'Energetic',
      'Generous',
      'Playful',
      'Approachable',
      'Bright',
    ],
    moods: ['Vibrant', 'Warm', 'Sunny', 'Festive', 'Energetic', 'Inviting', 'Lively', 'Autumnal'],
    symbolism: [
      'enthusiasm and creativity',
      'harvest and abundance',
      'warmth and hospitality',
      'adventure and change',
      'spiritual devotion in saffron robes',
      'the turning of autumn',
      'optimism and encouragement',
      'social energy and fun',
    ],
    uses: [
      'food and beverage branding',
      'call-to-action buttons',
      'autumn and harvest campaigns',
      'youth and sports brands',
      'safety and high-visibility gear',
      'travel and adventure marketing',
      'playful packaging',
      'warm interface highlights',
    ],
    keywords: [
      'Orange',
      'Citrus',
      'Warm',
      'Sunny',
      'Harvest',
      'Lively',
      'Autumn',
      'Friendly',
      'Zest',
      'Glow',
    ],
  },
  Yellow: {
    noun: 'yellow',
    range: [80, 118],
    undertones: ['a golden-orange undertone', 'a fresh green undertone'],
    hueWords: ['Yellow', 'Gold', 'Lemon', 'Canary', 'Honey', 'Butter', 'Mustard', 'Citrine'],
    nameNouns: [
      'Sunbeam',
      'Daffodil',
      'Buttercup',
      'Honeycomb',
      'Meadow',
      'Sunflower',
      'Lemonade',
      'Dandelion',
      'Goldfinch',
      'Custard',
      'Straw',
      'Wheatfield',
      'Saffron',
      'Chiffon',
      'Sunrise',
      'Pollen',
      'Mimosa',
      'Lantern',
      'Firefly',
      'Topaz',
    ],
    imagery: [
      'a field of sunflowers',
      'fresh lemons',
      'dripping honeycomb',
      'early morning sunlight',
      "a canary's feathers",
      'buttercups in a meadow',
      'golden wheat',
      'a dandelion head',
      'a classic school bus',
      'melted butter',
    ],
    emotions: [
      'Joyful',
      'Hopeful',
      'Cheerful',
      'Optimistic',
      'Playful',
      'Alert',
      'Confident',
      'Uplifted',
      'Curious',
      'Warm',
    ],
    personalities: [
      'Optimistic',
      'Spontaneous',
      'Friendly',
      'Energetic',
      'Witty',
      'Sunny',
      'Inventive',
      'Lighthearted',
      'Outgoing',
      'Curious',
    ],
    moods: ['Sunny', 'Bright', 'Uplifting', 'Radiant', 'Fresh', 'Playful', 'Golden', 'Lively'],
    symbolism: [
      'happiness and sunlight',
      'intellect and clarity',
      'hope and new beginnings',
      'caution and attention',
      'wealth and harvest',
      'friendship and warmth',
      'creativity and inspiration',
      'spring and renewal',
    ],
    uses: [
      'highlighting and annotation',
      "children's products",
      'caution and warning signage',
      'summer campaigns',
      'bakery and breakfast branding',
      'accent color on dark backgrounds',
      'cheerful packaging',
      'educational materials',
    ],
    keywords: [
      'Yellow',
      'Sunny',
      'Bright',
      'Cheerful',
      'Golden',
      'Light',
      'Happy',
      'Warm',
      'Sunshine',
      'Fresh',
    ],
  },
  Lime: {
    noun: 'yellow-green',
    range: [118, 135],
    undertones: ['a lemony undertone', 'a leafy green undertone'],
    hueWords: [
      'Lime',
      'Chartreuse',
      'Yellow-Green',
      'Pistachio',
      'Kiwi',
      'Citron',
      'Pear',
      'Apple Green',
    ],
    nameNouns: [
      'Sprout',
      'Lime',
      'Margarita',
      'Grasshopper',
      'Bud',
      'Kiwi',
      'Shoot',
      'Tendril',
      'Seedling',
      'Matcha',
      'Celery',
      'Absinthe',
      'Clover',
      'Zest',
      'Spring',
      'Wasabi',
      'Pear',
      'Lettuce',
      'Frond',
      'Bamboo',
    ],
    imagery: [
      'fresh lime zest',
      'new spring shoots',
      'a ripe pear',
      'sliced kiwi',
      'matcha foam',
      'a grasshopper in tall grass',
      'young bamboo',
      'wasabi paste',
      'crisp celery',
      'unfurling fern fronds',
    ],
    emotions: [
      'Refreshed',
      'Energized',
      'Playful',
      'Curious',
      'Lively',
      'Optimistic',
      'Spirited',
      'Awake',
      'Upbeat',
      'Youthful',
    ],
    personalities: [
      'Quirky',
      'Fresh',
      'Inventive',
      'Youthful',
      'Lively',
      'Unconventional',
      'Zesty',
      'Upbeat',
      'Curious',
      'Spirited',
    ],
    moods: ['Zesty', 'Fresh', 'Spring', 'Vivid', 'Crisp', 'Playful', 'Electric', 'Lively'],
    symbolism: [
      'new growth and youth',
      'freshness and vitality',
      'spring renewal',
      'zest and energy',
      'eccentricity and invention',
      'health and detox',
      'budding potential',
      'playful rebellion',
    ],
    uses: [
      'beverage and juice branding',
      'health and fitness products',
      'spring campaigns',
      'sports and outdoor gear',
      'tech product accents',
      "kids' products",
      'eco-friendly packaging',
      'vivid data highlights',
    ],
    keywords: [
      'Lime',
      'Zesty',
      'Fresh',
      'Spring',
      'Yellow-Green',
      'Crisp',
      'Vivid',
      'Sprout',
      'Lively',
      'Young',
    ],
  },
  Green: {
    noun: 'green',
    range: [135, 165],
    undertones: ['a warm yellow undertone', 'a cool blue undertone'],
    hueWords: [
      'Green',
      'Emerald',
      'Jade',
      'Viridian',
      'Shamrock',
      'Malachite',
      'Kelly Green',
      'Leaf Green',
    ],
    nameNouns: [
      'Meadow',
      'Grove',
      'Canopy',
      'Ivy',
      'Thicket',
      'Glade',
      'Spruce',
      'Clover',
      'Basil',
      'Pine',
      'Juniper',
      'Orchard',
      'Prairie',
      'Lagoon',
      'Shamrock',
      'Malachite',
      'Verdant',
      'Garden',
      'Rainforest',
      'Mint',
    ],
    imagery: [
      'a sunlit forest canopy',
      'fresh basil leaves',
      'a mossy riverbank',
      'polished jade',
      'a rolling meadow',
      'pine needles after rain',
      'a four-leaf clover',
      'ivy on old brick',
      'a tropical rainforest',
      'malachite stone',
    ],
    emotions: [
      'Calm',
      'Hopeful',
      'Balanced',
      'Refreshed',
      'Content',
      'Grounded',
      'Peaceful',
      'Restored',
      'Secure',
      'Optimistic',
    ],
    personalities: [
      'Balanced',
      'Nurturing',
      'Grounded',
      'Reliable',
      'Harmonious',
      'Patient',
      'Generous',
      'Steady',
      'Natural',
      'Kind',
    ],
    moods: [
      'Natural',
      'Fresh',
      'Lush',
      'Tranquil',
      'Restorative',
      'Verdant',
      'Peaceful',
      'Organic',
    ],
    symbolism: [
      'nature and growth',
      'renewal and hope',
      'health and healing',
      'prosperity and abundance',
      'harmony and balance',
      'environmental care',
      'fertility and life',
      'permission to go forward',
    ],
    uses: [
      'eco and sustainability branding',
      'success and confirmation states',
      'health and wellness products',
      'financial apps',
      'gardening and outdoor brands',
      'organic food packaging',
      'nature-inspired interiors',
      'calming interface accents',
    ],
    keywords: [
      'Green',
      'Nature',
      'Leafy',
      'Fresh',
      'Growth',
      'Eco',
      'Natural',
      'Lush',
      'Balanced',
      'Botanical',
    ],
  },
  Olive: {
    noun: 'olive',
    range: [100, 135],
    undertones: ['a golden undertone', 'a mossy green undertone'],
    hueWords: ['Olive', 'Moss', 'Khaki', 'Army Green', 'Sage', 'Lichen', 'Bronze Green', 'Drab'],
    nameNouns: [
      'Grove',
      'Bayleaf',
      'Thyme',
      'Lichen',
      'Bramble',
      'Fatigue',
      'Caper',
      'Artichoke',
      'Tapenade',
      'Marsh',
      'Bog',
      'Trail',
      'Canteen',
      'Hops',
      'Heath',
      'Rye',
      'Bark',
      'Field',
      'Saddle',
      'Tweed',
    ],
    imagery: [
      'cured green olives',
      'moss on a stone wall',
      'dried bay leaves',
      'a marsh at dusk',
      'military field canvas',
      'an artichoke heart',
      'heathland in late summer',
      'tapenade on rustic bread',
      'lichen on bark',
      'tweed fabric',
    ],
    emotions: [
      'Calm',
      'Grounded',
      'Steady',
      'Content',
      'Reflective',
      'Resilient',
      'Composed',
      'Patient',
      'Secure',
      'Earthy',
    ],
    personalities: [
      'Practical',
      'Resilient',
      'Down-to-Earth',
      'Mature',
      'Loyal',
      'Unpretentious',
      'Steady',
      'Wise',
      'Rugged',
      'Dependable',
    ],
    moods: ['Earthy', 'Rustic', 'Muted', 'Mediterranean', 'Rugged', 'Natural', 'Woodland', 'Quiet'],
    symbolism: [
      'peace through the olive branch',
      'endurance and resilience',
      'earthiness and tradition',
      'Mediterranean life',
      'camouflage and service',
      'patience and maturity',
      'harvest and preservation',
      'quiet wisdom',
    ],
    uses: [
      'outdoor and utility apparel',
      'Mediterranean food branding',
      'earthy interior palettes',
      'natural cosmetics',
      'camping and hiking gear',
      'rustic packaging',
      'muted interface accents',
      'heritage brands',
    ],
    keywords: [
      'Olive',
      'Earthy',
      'Moss',
      'Muted',
      'Rustic',
      'Natural',
      'Khaki',
      'Grounded',
      'Utility',
      'Woodland',
    ],
  },
  Teal: {
    noun: 'teal',
    range: [165, 220],
    undertones: ['a green undertone', 'a blue undertone'],
    hueWords: [
      'Teal',
      'Peacock',
      'Petrol',
      'Spruce',
      'Lagoon',
      'Deep Teal',
      'Blue-Green',
      'Sea Green',
    ],
    nameNouns: [
      'Lagoon',
      'Fjord',
      'Peacock',
      'Kelp',
      'Tidepool',
      'Mallard',
      'Reef',
      'Harbor',
      'Estuary',
      'Marina',
      'Grotto',
      'Current',
      'Abyss',
      'Patina',
      'Verdigris',
      'Spruce',
      'Seaglass',
      'Cove',
      'Undertow',
      'Bayou',
    ],
    imagery: [
      'a deep tropical lagoon',
      'peacock feathers',
      'copper patina',
      'a kelp forest',
      'a shaded tide pool',
      "a mallard's head",
      'a Nordic fjord',
      'weathered seaglass',
      'a quiet marina',
      'a reef at depth',
    ],
    emotions: [
      'Calm',
      'Composed',
      'Balanced',
      'Thoughtful',
      'Assured',
      'Serene',
      'Focused',
      'Reflective',
      'Steady',
      'Clear',
    ],
    personalities: [
      'Sophisticated',
      'Balanced',
      'Calm',
      'Independent',
      'Thoughtful',
      'Discerning',
      'Open',
      'Composed',
      'Professional',
      'Reliable',
    ],
    moods: ['Cool', 'Deep', 'Coastal', 'Grounded', 'Calm', 'Oceanic', 'Refined', 'Tranquil'],
    symbolism: [
      'balance and clarity',
      'depth and sophistication',
      "the ocean's calm",
      'emotional healing',
      'open communication',
      'renewal from water',
      'quiet confidence',
      'protection and wisdom',
    ],
    uses: [
      'healthcare and wellness brands',
      'corporate identities',
      'coastal and spa interiors',
      'dashboards and data visualization',
      'dark-mode accents',
      'premium packaging',
      'tech branding',
      'calm interface highlights',
    ],
    keywords: [
      'Teal',
      'Blue-Green',
      'Deep',
      'Coastal',
      'Calm',
      'Cool',
      'Ocean',
      'Balanced',
      'Refined',
      'Sea',
    ],
  },
  Cyan: {
    noun: 'aqua',
    range: [165, 220],
    undertones: ['a minty green undertone', 'a sky-blue undertone'],
    hueWords: ['Aqua', 'Turquoise', 'Cyan', 'Seafoam', 'Lagoon', 'Pool', 'Glacier', 'Aquamarine'],
    nameNouns: [
      'Lagoon',
      'Splash',
      'Seafoam',
      'Glacier',
      'Pool',
      'Surf',
      'Spray',
      'Shallows',
      'Atoll',
      'Breeze',
      'Mermaid',
      'Ripple',
      'Wave',
      'Iceberg',
      'Fountain',
      'Oasis',
      'Tide',
      'Cascade',
      'Frost',
      'Bay',
    ],
    imagery: [
      'shallow tropical water',
      'sea foam on the shore',
      'a swimming pool in summer',
      'glacial meltwater',
      'an aquamarine gem',
      'a turquoise stone',
      'a breaking wave',
      'a desert oasis',
      'frost on glass',
      'a Caribbean atoll',
    ],
    emotions: [
      'Refreshed',
      'Serene',
      'Joyful',
      'Calm',
      'Clear',
      'Uplifted',
      'Relaxed',
      'Free',
      'Soothed',
      'Light',
    ],
    personalities: [
      'Friendly',
      'Communicative',
      'Clear',
      'Fresh',
      'Easygoing',
      'Creative',
      'Open',
      'Gentle',
      'Breezy',
      'Bright',
    ],
    moods: ['Tropical', 'Fresh', 'Breezy', 'Cool', 'Airy', 'Clean', 'Aquatic', 'Bright'],
    symbolism: [
      'clarity and refreshment',
      'tropical escape',
      'clean water and health',
      'friendship and protection',
      'calm communication',
      'the open sea',
      'healing and balance',
      'lightness of spirit',
    ],
    uses: [
      'travel and resort branding',
      'pool and spa themes',
      'summer campaigns',
      'healthcare interfaces',
      'beverage packaging',
      'swimwear and beachwear',
      'tech accents',
      'fresh background tints',
    ],
    keywords: [
      'Aqua',
      'Turquoise',
      'Fresh',
      'Tropical',
      'Water',
      'Cool',
      'Clear',
      'Breezy',
      'Sea',
      'Light',
    ],
  },
  Blue: {
    noun: 'blue',
    range: [220, 280],
    undertones: ['a cyan undertone', 'a violet undertone'],
    hueWords: ['Blue', 'Azure', 'Cobalt', 'Sapphire', 'Navy', 'Denim', 'Cornflower', 'Sky'],
    nameNouns: [
      'Harbor',
      'Horizon',
      'Glacier',
      'Tide',
      'Lake',
      'Twilight',
      'Atlantic',
      'Mariner',
      'Delphinium',
      'Bluebird',
      'Indigo',
      'Denim',
      'Storm',
      'Fjord',
      'Nightfall',
      'Riverbed',
      'Porcelain',
      'Hydrangea',
      'Starling',
      'Monsoon',
    ],
    imagery: [
      'a clear midday sky',
      'deep ocean water',
      'cobalt glass',
      'faded denim',
      'a sapphire gemstone',
      "a bluebird's wing",
      'hydrangea blossoms',
      'a mountain lake',
      'Delft porcelain',
      'a summer storm cloud',
    ],
    emotions: [
      'Calm',
      'Trusting',
      'Serene',
      'Confident',
      'Peaceful',
      'Focused',
      'Secure',
      'Reflective',
      'Hopeful',
      'Composed',
    ],
    personalities: [
      'Trustworthy',
      'Loyal',
      'Dependable',
      'Calm',
      'Intelligent',
      'Sincere',
      'Steady',
      'Responsible',
      'Wise',
      'Open',
    ],
    moods: ['Tranquil', 'Cool', 'Open', 'Serene', 'Deep', 'Clear', 'Steady', 'Airy'],
    symbolism: [
      'trust and loyalty',
      'sky and sea',
      'peace and calm',
      'wisdom and stability',
      'authority and confidence',
      'truth and sincerity',
      'freedom and openness',
      'depth and reflection',
    ],
    uses: [
      'corporate and financial branding',
      'technology products',
      'healthcare interfaces',
      'hyperlinks and primary buttons',
      'nautical themes',
      'uniforms and workwear',
      'calm interior design',
      'data visualization',
    ],
    keywords: [
      'Blue',
      'Calm',
      'Trust',
      'Sky',
      'Ocean',
      'Cool',
      'Serene',
      'Reliable',
      'Deep',
      'Clear',
    ],
  },
  Indigo: {
    noun: 'indigo',
    range: [280, 300],
    undertones: ['a deep blue undertone', 'a violet undertone'],
    hueWords: ['Indigo', 'Violet', 'Iris', 'Periwinkle', 'Ink', 'Lapis', 'Twilight', 'Ultramarine'],
    nameNouns: [
      'Iris',
      'Nightshade',
      'Twilight',
      'Dusk',
      'Lapis',
      'Inkwell',
      'Galaxy',
      'Nebula',
      'Velvet',
      'Amethyst',
      'Hyacinth',
      'Starlight',
      'Midnight',
      'Orbit',
      'Dreamscape',
      'Larkspur',
      'Cosmos',
      'Aurora',
      'Gemstone',
      'Mystic',
    ],
    imagery: [
      'a twilight sky',
      'an iris petal',
      'indigo-dyed cloth',
      'lapis lazuli',
      'a distant nebula',
      'a bottle of ink',
      'larkspur blooms',
      'an amethyst geode',
      'the edge of a rainbow',
      'velvet drapes at night',
    ],
    emotions: [
      'Intuitive',
      'Contemplative',
      'Mystical',
      'Calm',
      'Inspired',
      'Dreamy',
      'Curious',
      'Reverent',
      'Focused',
      'Introspective',
    ],
    personalities: [
      'Wise',
      'Intuitive',
      'Imaginative',
      'Spiritual',
      'Visionary',
      'Thoughtful',
      'Mysterious',
      'Idealistic',
      'Deep',
      'Perceptive',
    ],
    moods: [
      'Mystical',
      'Nocturnal',
      'Dreamy',
      'Deep',
      'Cosmic',
      'Quiet',
      'Enchanted',
      'Contemplative',
    ],
    symbolism: [
      'intuition and insight',
      'spiritual depth',
      'night and the cosmos',
      'imagination and dreams',
      'perception beyond the obvious',
      'devotion and integrity',
      'mystery and the unknown',
      'wisdom earned through reflection',
    ],
    uses: [
      'meditation and wellness apps',
      'night and astronomy themes',
      'fantasy illustration',
      'music and creative brands',
      'premium packaging',
      'dark-mode accents',
      'spiritual and cultural design',
      'evening fashion',
    ],
    keywords: [
      'Indigo',
      'Violet',
      'Twilight',
      'Mystic',
      'Deep',
      'Cosmic',
      'Dreamy',
      'Intuitive',
      'Night',
      'Velvet',
    ],
  },
  Purple: {
    noun: 'purple',
    range: [300, 330],
    undertones: ['a blue-violet undertone', 'a reddish undertone'],
    hueWords: ['Purple', 'Plum', 'Amethyst', 'Grape', 'Orchid', 'Lilac', 'Mulberry', 'Heather'],
    nameNouns: [
      'Amethyst',
      'Mulberry',
      'Orchid',
      'Heather',
      'Lilac',
      'Wisteria',
      'Grape',
      'Eggplant',
      'Monarch',
      'Velvet',
      'Crown',
      'Lavender',
      'Elderberry',
      'Thistle',
      'Sorcery',
      'Tyrian',
      'Fig',
      'Bramble',
      'Jubilee',
      'Opal',
    ],
    imagery: [
      'a cluster of ripe grapes',
      'wisteria in bloom',
      'an amethyst crystal',
      'heather on the moors',
      'a velvet royal robe',
      'fresh figs',
      'lilac blossoms',
      'a ripe eggplant',
      'elderberries',
      "a crown's velvet lining",
    ],
    emotions: [
      'Imaginative',
      'Dignified',
      'Mysterious',
      'Romantic',
      'Inspired',
      'Wistful',
      'Creative',
      'Proud',
      'Enchanted',
      'Tender',
    ],
    personalities: [
      'Creative',
      'Regal',
      'Imaginative',
      'Ambitious',
      'Sensitive',
      'Artistic',
      'Unique',
      'Graceful',
      'Independent',
      'Wise',
    ],
    moods: ['Regal', 'Luxurious', 'Mystical', 'Dreamy', 'Romantic', 'Rich', 'Whimsical', 'Elegant'],
    symbolism: [
      'royalty and nobility',
      'creativity and imagination',
      'spirituality and mystery',
      'luxury and ambition',
      'dignity and pride',
      'magic and fantasy',
      'transformation',
      'remembrance and grace',
    ],
    uses: [
      'luxury and beauty branding',
      'creative and artistic brands',
      'wedding palettes',
      'fantasy and game design',
      'wellness and spa products',
      'premium packaging',
      'floral design',
      'expressive interface accents',
    ],
    keywords: [
      'Purple',
      'Royal',
      'Regal',
      'Creative',
      'Mystic',
      'Luxury',
      'Plum',
      'Floral',
      'Rich',
      'Dreamy',
    ],
  },
  Magenta: {
    noun: 'magenta',
    range: [330, 352],
    undertones: ['a purple undertone', 'a raspberry-red undertone'],
    hueWords: [
      'Magenta',
      'Fuchsia',
      'Raspberry',
      'Berry',
      'Cerise',
      'Boysenberry',
      'Peony',
      'Orchid',
    ],
    nameNouns: [
      'Peony',
      'Bougainvillea',
      'Raspberry',
      'Dragonfruit',
      'Hibiscus',
      'Cerise',
      'Berry',
      'Sangria',
      'Flamingo',
      'Jam',
      'Carnival',
      'Neon',
      'Lipstick',
      'Cosmo',
      'Azalea',
      'Beet',
      'Sorbet',
      'Cabaret',
      'Bloom',
      'Mulberry',
    ],
    imagery: [
      'bougainvillea in full bloom',
      'a sliced dragonfruit',
      'raspberry jam',
      'a hibiscus flower',
      'a neon sign at night',
      'a peony bud',
      'fresh beets',
      'a carnival costume',
      'berry sorbet',
      'bold lipstick',
    ],
    emotions: [
      'Exuberant',
      'Passionate',
      'Daring',
      'Playful',
      'Confident',
      'Excited',
      'Flirtatious',
      'Spirited',
      'Joyful',
      'Fearless',
    ],
    personalities: [
      'Unconventional',
      'Charismatic',
      'Expressive',
      'Bold',
      'Creative',
      'Theatrical',
      'Vivacious',
      'Daring',
      'Outgoing',
      'Free-Spirited',
    ],
    moods: ['Electric', 'Festive', 'Vivid', 'Playful', 'Lush', 'Dramatic', 'Exotic', 'Bold'],
    symbolism: [
      'nonconformity and creativity',
      'joyful celebration',
      'passion with playfulness',
      'compassion and kindness',
      'transformation and change',
      'tropical abundance',
      'confidence and self-expression',
      'emotional balance between red and violet',
    ],
    uses: [
      'fashion and beauty campaigns',
      'event and festival posters',
      'music and nightlife branding',
      'cosmetics packaging',
      'pop-art graphics',
      'bold interface accents',
      'tropical product lines',
      'celebration and party themes',
    ],
    keywords: [
      'Magenta',
      'Fuchsia',
      'Berry',
      'Vivid',
      'Bold',
      'Playful',
      'Electric',
      'Floral',
      'Pop',
      'Festive',
    ],
  },
  Pink: {
    noun: 'pink',
    range: [330, 40],
    undertones: ['a cool lilac undertone', 'a warm peachy undertone'],
    hueWords: ['Pink', 'Rose', 'Blush', 'Petal', 'Coral', 'Salmon', 'Peony', 'Flamingo'],
    nameNouns: [
      'Blossom',
      'Petal',
      'Ballet',
      'Cotton Candy',
      'Rosebud',
      'Peony',
      'Sakura',
      'Flamingo',
      'Seashell',
      'Bonbon',
      'Macaron',
      'Camellia',
      'Grapefruit',
      'Taffy',
      'Cupcake',
      'Daydream',
      'Lullaby',
      'Magnolia',
      'Sorbet',
      'Blush',
    ],
    imagery: [
      'cherry blossoms in spring',
      'a ballet slipper',
      'cotton candy at a fair',
      'a rose petal',
      'the inside of a seashell',
      'a strawberry macaron',
      'flamingo feathers',
      'a magnolia bloom',
      'pink grapefruit',
      'a sunrise over the sea',
    ],
    emotions: [
      'Tender',
      'Affectionate',
      'Sweet',
      'Playful',
      'Gentle',
      'Romantic',
      'Cheerful',
      'Comforted',
      'Nostalgic',
      'Hopeful',
    ],
    personalities: [
      'Kind',
      'Nurturing',
      'Gentle',
      'Romantic',
      'Warm',
      'Compassionate',
      'Playful',
      'Sensitive',
      'Charming',
      'Approachable',
    ],
    moods: ['Soft', 'Romantic', 'Sweet', 'Delicate', 'Playful', 'Dreamy', 'Gentle', 'Warm'],
    symbolism: [
      'affection and care',
      'romance and tenderness',
      'innocence and youth',
      'compassion and nurturing',
      'playfulness and joy',
      'spring and blossoming',
      'femininity and grace',
      'hope and healing',
    ],
    uses: [
      'cosmetics and skincare packaging',
      'bakery and confectionery branding',
      'wedding stationery',
      'baby and nursery products',
      'fashion accessories',
      'soft interface backgrounds',
      'floral design',
      'self-care brands',
    ],
    keywords: [
      'Pink',
      'Rose',
      'Blush',
      'Soft',
      'Sweet',
      'Romantic',
      'Petal',
      'Gentle',
      'Floral',
      'Tender',
    ],
  },
  Brown: {
    noun: 'brown',
    range: [35, 100],
    undertones: ['a reddish undertone', 'a golden undertone'],
    hueWords: ['Brown', 'Cocoa', 'Mocha', 'Chestnut', 'Walnut', 'Umber', 'Caramel', 'Toffee'],
    nameNouns: [
      'Saddle',
      'Walnut',
      'Espresso',
      'Acorn',
      'Cinnamon',
      'Leather',
      'Timber',
      'Hazelnut',
      'Truffle',
      'Bark',
      'Cocoa',
      'Pecan',
      'Gingerbread',
      'Molasses',
      'Cedar',
      'Burlap',
      'Canyon',
      'Clay',
      'Tobacco',
      'Mahogany',
    ],
    imagery: [
      'a freshly brewed espresso',
      'polished walnut wood',
      'a worn leather saddle',
      'cinnamon sticks',
      'autumn acorns',
      'a cocoa bean',
      'rich garden soil',
      'a mahogany desk',
      'caramel sauce',
      'canyon rock at sunset',
    ],
    emotions: [
      'Secure',
      'Comforted',
      'Grounded',
      'Content',
      'Warm',
      'Steady',
      'Nostalgic',
      'Relaxed',
      'Reassured',
      'Cozy',
    ],
    personalities: [
      'Reliable',
      'Honest',
      'Down-to-Earth',
      'Supportive',
      'Practical',
      'Humble',
      'Dependable',
      'Rugged',
      'Warm',
      'Sincere',
    ],
    moods: ['Cozy', 'Rustic', 'Earthy', 'Warm', 'Autumnal', 'Grounded', 'Homey', 'Natural'],
    symbolism: [
      'stability and reliability',
      'earth and soil',
      'comfort and home',
      'craftsmanship and tradition',
      'autumn and harvest',
      'simplicity and honesty',
      'resilience and endurance',
      'warmth and nourishment',
    ],
    uses: [
      'coffee and chocolate branding',
      'leather goods and accessories',
      'furniture and woodcraft',
      'rustic interiors',
      'outdoor and heritage brands',
      'autumn campaigns',
      'natural product packaging',
      'warm typography',
    ],
    keywords: [
      'Brown',
      'Earthy',
      'Wood',
      'Leather',
      'Warm',
      'Rustic',
      'Cozy',
      'Natural',
      'Coffee',
      'Grounded',
    ],
  },
  Beige: {
    noun: 'beige',
    range: [30, 115],
    undertones: ['a rosy undertone', 'a golden undertone'],
    hueWords: ['Beige', 'Sand', 'Cream', 'Oat', 'Linen', 'Ecru', 'Biscuit', 'Taupe'],
    nameNouns: [
      'Oatmeal',
      'Driftwood',
      'Parchment',
      'Dune',
      'Biscuit',
      'Latte',
      'Linen',
      'Sandstone',
      'Shortbread',
      'Porcelain',
      'Almond',
      'Muslin',
      'Seashore',
      'Pebble',
      'Chamomile',
      'Vanilla',
      'Flax',
      'Meringue',
      'Cashmere',
      'Raffia',
    ],
    imagery: [
      'warm sand at noon',
      'a bowl of oatmeal',
      'unbleached linen',
      "a latte's foam",
      'aged parchment',
      'smooth driftwood',
      'fresh shortbread',
      'a sandstone wall',
      'cashmere knitwear',
      'a vanilla bean pod',
    ],
    emotions: [
      'Calm',
      'Comforted',
      'Relaxed',
      'Content',
      'Secure',
      'Gentle',
      'Peaceful',
      'Grounded',
      'Reassured',
      'Easy',
    ],
    personalities: [
      'Understated',
      'Reliable',
      'Modest',
      'Practical',
      'Gentle',
      'Classic',
      'Warm',
      'Unfussy',
      'Calm',
      'Approachable',
    ],
    moods: ['Neutral', 'Soft', 'Cozy', 'Natural', 'Quiet', 'Warm', 'Organic', 'Minimal'],
    symbolism: [
      'simplicity and calm',
      'natural materials',
      'comfort and warmth',
      'timeless neutrality',
      'humility and dependability',
      'the seashore and sand',
      'quiet elegance',
      'a restful pause',
    ],
    uses: [
      'neutral interior palettes',
      'natural and organic packaging',
      'fashion basics',
      'page and card backgrounds',
      'wedding stationery',
      'skincare and wellness branding',
      'bakery and café design',
      'minimal brand systems',
    ],
    keywords: [
      'Beige',
      'Neutral',
      'Sand',
      'Cream',
      'Soft',
      'Natural',
      'Warm',
      'Calm',
      'Linen',
      'Minimal',
    ],
  },
  Gray: {
    noun: 'gray',
    range: null,
    undertones: ['', ''],
    hueWords: ['Gray', 'Slate', 'Ash', 'Pewter', 'Stone', 'Smoke', 'Graphite', 'Silver'],
    nameNouns: [
      'Pebble',
      'Granite',
      'Fog',
      'Pewter',
      'Concrete',
      'Ash',
      'Flint',
      'Overcast',
      'Drizzle',
      'Stone',
      'Harbor',
      'Shale',
      'Mist',
      'Zinc',
      'Cobblestone',
      'Gravel',
      'Smoke',
      'Moonstone',
      'Steel',
      'Dove',
    ],
    imagery: [
      'a foggy morning',
      'river pebbles',
      'polished pewter',
      'a rainy city street',
      "a dove's wing",
      'weathered granite',
      'wood ash',
      'an overcast sky',
      'brushed steel',
      'cobblestones after rain',
    ],
    emotions: [
      'Calm',
      'Neutral',
      'Composed',
      'Reflective',
      'Steady',
      'Reserved',
      'Balanced',
      'Pensive',
      'Quiet',
      'Contemplative',
    ],
    personalities: [
      'Balanced',
      'Practical',
      'Reserved',
      'Mature',
      'Impartial',
      'Sophisticated',
      'Calm',
      'Discreet',
      'Dependable',
      'Modest',
    ],
    moods: ['Muted', 'Calm', 'Neutral', 'Quiet', 'Industrial', 'Overcast', 'Minimal', 'Subdued'],
    symbolism: [
      'neutrality and balance',
      'maturity and wisdom',
      'compromise and calm',
      'industry and modernity',
      'stone and permanence',
      'restraint and discretion',
      'fog and uncertainty',
      'timeless sophistication',
    ],
    uses: [
      'interface neutrals and borders',
      'secondary text and icons',
      'minimal and modern interiors',
      'corporate design systems',
      'industrial and tech branding',
      'photography backdrops',
      'disabled and inactive states',
      'suiting and outerwear',
    ],
    keywords: [
      'Gray',
      'Neutral',
      'Stone',
      'Muted',
      'Calm',
      'Minimal',
      'Modern',
      'Quiet',
      'Balanced',
      'Industrial',
    ],
  },
  Black: {
    noun: 'near-black',
    range: null,
    undertones: ['', ''],
    hueWords: ['Black', 'Onyx', 'Jet', 'Ebony', 'Obsidian', 'Ink', 'Coal', 'Raven'],
    nameNouns: [
      'Midnight',
      'Obsidian',
      'Onyx',
      'Raven',
      'Inkwell',
      'Abyss',
      'Eclipse',
      'Coal',
      'Shadow',
      'Void',
      'Panther',
      'Tar',
      'Licorice',
      'Soot',
      'Caviar',
      'Nightfall',
      'Vinyl',
      'Graphite',
      'Jet',
      'Eclipse',
    ],
    imagery: [
      'a moonless night',
      'polished obsidian',
      "a raven's feathers",
      'fresh ink',
      'a lump of coal',
      'a vinyl record',
      'black licorice',
      'the depths of a cave',
      'a solar eclipse',
      'jet beads',
    ],
    emotions: [
      'Powerful',
      'Serious',
      'Mysterious',
      'Confident',
      'Composed',
      'Somber',
      'Intense',
      'Protected',
      'Focused',
      'Formal',
    ],
    personalities: [
      'Sophisticated',
      'Authoritative',
      'Mysterious',
      'Elegant',
      'Strong',
      'Independent',
      'Serious',
      'Disciplined',
      'Bold',
      'Enigmatic',
    ],
    moods: ['Dramatic', 'Formal', 'Mysterious', 'Sleek', 'Nocturnal', 'Elegant', 'Intense', 'Deep'],
    symbolism: [
      'power and authority',
      'elegance and formality',
      'mystery and the unknown',
      'mourning and solemnity',
      'protection and strength',
      'rebellion and edge',
      'night and rest',
      'sophistication',
    ],
    uses: [
      'typography and body text',
      'luxury branding',
      'formal and evening wear',
      'dark-mode surfaces',
      'high-contrast design',
      'premium packaging',
      'photography and portfolio sites',
      'minimal graphic design',
    ],
    keywords: [
      'Black',
      'Dark',
      'Elegant',
      'Formal',
      'Mystery',
      'Bold',
      'Night',
      'Sleek',
      'Deep',
      'Classic',
    ],
  },
  White: {
    noun: 'off-white',
    range: null,
    undertones: ['', ''],
    hueWords: ['White', 'Snow', 'Pearl', 'Porcelain', 'Chalk', 'Cotton', 'Frost', 'Alabaster'],
    nameNouns: [
      'Pearl',
      'Porcelain',
      'Cloud',
      'Snowdrop',
      'Cotton',
      'Chalk',
      'Alabaster',
      'Frost',
      'Moonbeam',
      'Meringue',
      'Feather',
      'Lily',
      'Eggshell',
      'Gardenia',
      'Bone',
      'Coconut',
      'Marble',
      'Sugar',
      'Vapor',
      'Ivory',
    ],
    imagery: [
      'fresh snowfall',
      "a pearl's luster",
      'fine porcelain',
      'a summer cloud',
      'crisp cotton sheets',
      'a white gardenia',
      'polished marble',
      'an eggshell',
      'chalk on slate',
      'morning frost',
    ],
    emotions: [
      'Calm',
      'Clear',
      'Peaceful',
      'Fresh',
      'Hopeful',
      'Light',
      'Pure',
      'Open',
      'Serene',
      'Gentle',
    ],
    personalities: [
      'Pure',
      'Minimal',
      'Honest',
      'Calm',
      'Refined',
      'Clean',
      'Modest',
      'Graceful',
      'Open',
      'Simple',
    ],
    moods: ['Clean', 'Airy', 'Light', 'Minimal', 'Fresh', 'Serene', 'Bright', 'Quiet'],
    symbolism: [
      'purity and new beginnings',
      'peace and simplicity',
      'cleanliness and clarity',
      'light and openness',
      'weddings and ceremony',
      'mourning in parts of East Asia',
      'space and possibility',
      'honesty',
    ],
    uses: [
      'page and app backgrounds',
      'negative space',
      'wedding design',
      'healthcare and clean-tech branding',
      'minimal interiors',
      'product photography backdrops',
      'text on dark surfaces',
      'luxury stationery',
    ],
    keywords: [
      'White',
      'Clean',
      'Light',
      'Pure',
      'Airy',
      'Minimal',
      'Soft',
      'Bright',
      'Fresh',
      'Neutral',
    ],
  },
};

export type LightBand = 'very dark' | 'dark' | 'medium' | 'light' | 'pale';
export type ChromaBand = 'grayish' | 'muted' | 'moderate' | 'strong' | 'vivid';

export type Band = {
  adjectives: string[];
  nameModifiers: string[];
  /** Short factual follow-up sentences for descriptions. */
  notes: string[];
  emotions: string[];
  personalities: string[];
  moods: string[];
  symbolism: string[];
  uses: string[];
  keywords: string[];
};

export const LIGHT_BANDS: Record<LightBand, Band> = {
  'very dark': {
    adjectives: ['very deep', 'nearly black', 'shadowed', 'inky'],
    nameModifiers: [
      'Midnight',
      'Shadow',
      'Nocturne',
      'Moonless',
      'Inky',
      'Darkest',
      'Night',
      'Starless',
    ],
    notes: [
      'It reads as nearly black in low light.',
      'It works best as a deep base or text color.',
      'Its color shows most clearly beside lighter tones.',
    ],
    emotions: ['Serious', 'Intense', 'Introspective', 'Somber'],
    personalities: ['Enigmatic', 'Reserved', 'Powerful', 'Stoic'],
    moods: ['Nocturnal', 'Brooding', 'Deep', 'Dramatic'],
    symbolism: ['depth and mystery', 'gravity and seriousness', 'night and stillness'],
    uses: ['dark-mode surfaces', 'typography', 'luxury packaging'],
    keywords: ['Dark', 'Deep', 'Shadowed', 'Night'],
  },
  dark: {
    adjectives: ['deep', 'dark', 'rich', 'dusky'],
    nameModifiers: ['Deep', 'Dark', 'Dusky', 'Twilight', 'Velvet', 'Smoldering', 'Rich', 'Stormy'],
    notes: [
      'It carries white text comfortably.',
      'Its depth gives layouts a grounded anchor.',
      'It holds its color well in print and on screen.',
    ],
    emotions: ['Composed', 'Serious', 'Grounded', 'Resolute'],
    personalities: ['Authoritative', 'Steadfast', 'Mature', 'Dignified'],
    moods: ['Rich', 'Moody', 'Dramatic', 'Formal'],
    symbolism: ['strength and maturity', 'tradition and authority', 'depth and substance'],
    uses: ['headers and navigation bars', 'formal branding', 'accent walls'],
    keywords: ['Deep', 'Rich', 'Dark', 'Moody'],
  },
  medium: {
    adjectives: ['medium', 'mid-tone', 'balanced', 'true'],
    nameModifiers: [
      'True',
      'Classic',
      'Heritage',
      'Painted',
      'Glazed',
      'Woven',
      'Tapestry',
      'Ceramic',
    ],
    notes: [
      'Its mid-tone value suits both light and dark surroundings.',
      'It sits comfortably in the middle of a tonal scale.',
      'It works as a dependable primary color.',
    ],
    emotions: ['Balanced', 'Steady', 'Assured', 'Content'],
    personalities: ['Balanced', 'Approachable', 'Dependable', 'Confident'],
    moods: ['Balanced', 'Natural', 'Steady', 'Clear'],
    symbolism: ['balance and dependability', 'everyday honesty', 'steady confidence'],
    uses: ['primary brand colors', 'illustration', 'charts and data visualization'],
    keywords: ['Medium', 'Balanced', 'Classic', 'True'],
  },
  light: {
    adjectives: ['light', 'soft', 'airy', 'sunlit'],
    nameModifiers: ['Soft', 'Light', 'Sunlit', 'Morning', 'Gentle', 'Breezy', 'Bright', 'Spring'],
    notes: [
      'It pairs well with dark text.',
      'Its lightness keeps compositions open and friendly.',
      'It brightens a palette without overwhelming it.',
    ],
    emotions: ['Cheerful', 'Gentle', 'Uplifted', 'Relaxed'],
    personalities: ['Friendly', 'Easygoing', 'Gentle', 'Optimistic'],
    moods: ['Light', 'Airy', 'Fresh', 'Bright'],
    symbolism: ['openness and ease', 'freshness and optimism', 'gentle warmth'],
    uses: ['secondary backgrounds', 'illustration fills', 'spring and summer collections'],
    keywords: ['Light', 'Soft', 'Airy', 'Fresh'],
  },
  pale: {
    adjectives: ['pale', 'whisper-light', 'pastel', 'delicate'],
    nameModifiers: ['Pale', 'Whisper', 'Misty', 'Powder', 'Faded', 'Frosted', 'Chalk', 'Hazy'],
    notes: [
      'It is light enough to serve as a background tint.',
      'Its color is a subtle wash rather than a statement.',
      'It reads almost white beside saturated colors.',
    ],
    emotions: ['Serene', 'Tender', 'Peaceful', 'Soothed'],
    personalities: ['Delicate', 'Gentle', 'Quiet', 'Graceful'],
    moods: ['Soft', 'Ethereal', 'Delicate', 'Calm'],
    symbolism: ['innocence and softness', 'calm and rest', 'quiet hope'],
    uses: ['page backgrounds', 'nursery decor', 'stationery and invitations'],
    keywords: ['Pale', 'Pastel', 'Delicate', 'Soft'],
  },
};

export const CHROMA_BANDS: Record<ChromaBand, Band> = {
  grayish: {
    adjectives: ['grayed', 'smoky', 'ashen', 'weathered'],
    nameModifiers: ['Smoky', 'Ashen', 'Weathered', 'Foggy', 'Stone', 'Dusty', 'Muted', 'Hazy'],
    notes: [
      'Its hue is restrained, close to a tinted neutral.',
      'It behaves like a neutral with a hint of color.',
    ],
    emotions: ['Calm', 'Reserved', 'Pensive', 'Neutral'],
    personalities: ['Understated', 'Discreet', 'Thoughtful', 'Modest'],
    moods: ['Subdued', 'Muted', 'Quiet', 'Overcast'],
    symbolism: ['restraint and subtlety', 'weathered endurance', 'quiet sophistication'],
    uses: ['neutral design systems', 'minimal interiors', 'understated fashion'],
    keywords: ['Grayish', 'Muted', 'Smoky', 'Subtle'],
  },
  muted: {
    adjectives: ['muted', 'dusty', 'soft-toned', 'mellow'],
    nameModifiers: ['Dusty', 'Faded', 'Mellow', 'Vintage', 'Antique', 'Washed', 'Worn', 'Hushed'],
    notes: [
      'Its softened saturation feels lived-in and calm.',
      'It blends easily with natural materials.',
    ],
    emotions: ['Nostalgic', 'Calm', 'Content', 'Mellow'],
    personalities: ['Gentle', 'Easygoing', 'Sentimental', 'Unhurried'],
    moods: ['Vintage', 'Mellow', 'Earthy', 'Relaxed'],
    symbolism: ['nostalgia and memory', 'comfort and ease', 'aged elegance'],
    uses: ['vintage-inspired branding', 'home textiles', 'editorial layouts'],
    keywords: ['Muted', 'Dusty', 'Vintage', 'Mellow'],
  },
  moderate: {
    adjectives: ['clear', 'natural', 'even', 'pleasant'],
    nameModifiers: ['Clear', 'Natural', 'Fresh', 'Pure', 'Country', 'Garden', 'Orchard', 'Folk'],
    notes: [
      'Its saturation is balanced, neither loud nor dull.',
      'It reads as a natural, unforced color.',
    ],
    emotions: ['Pleasant', 'Content', 'Balanced', 'Easy'],
    personalities: ['Approachable', 'Sincere', 'Natural', 'Friendly'],
    moods: ['Natural', 'Pleasant', 'Fresh', 'Clear'],
    symbolism: ['natural harmony', 'sincerity', 'everyday comfort'],
    uses: ['brand palettes', 'product packaging', 'interface accents'],
    keywords: ['Natural', 'Clear', 'Fresh', 'Pleasant'],
  },
  strong: {
    adjectives: ['strong', 'saturated', 'rich', 'bold'],
    nameModifiers: ['Bold', 'Rich', 'Royal', 'Jewel', 'Bright', 'Lush', 'Ripe', 'Glossy'],
    notes: [
      'Its strong saturation gives it presence.',
      'It holds attention without tipping into neon.',
    ],
    emotions: ['Confident', 'Energized', 'Proud', 'Determined'],
    personalities: ['Bold', 'Confident', 'Expressive', 'Spirited'],
    moods: ['Vibrant', 'Lush', 'Rich', 'Lively'],
    symbolism: ['confidence and vitality', 'abundance', 'bold expression'],
    uses: ['logos and brand marks', 'feature highlights', 'statement decor'],
    keywords: ['Bold', 'Rich', 'Saturated', 'Vibrant'],
  },
  vivid: {
    adjectives: ['vivid', 'electric', 'brilliant', 'intense'],
    nameModifiers: [
      'Electric',
      'Neon',
      'Radiant',
      'Brilliant',
      'Blazing',
      'Vivid',
      'Dazzling',
      'Bright',
    ],
    notes: [
      'It is near the saturation limit of standard screens.',
      'Its intensity makes it stand out instantly, so use it sparingly.',
    ],
    emotions: ['Exhilarated', 'Excited', 'Thrilled', 'Daring'],
    personalities: ['Fearless', 'Energetic', 'Unconventional', 'Dynamic'],
    moods: ['Electric', 'Intense', 'Loud', 'Dazzling'],
    symbolism: ['excitement and energy', 'attention and urgency', 'modern digital culture'],
    uses: ['call-to-action buttons', 'event posters', 'sportswear'],
    keywords: ['Vivid', 'Electric', 'Intense', 'Neon'],
  },
};

/** Category tone labels by lightness and chroma band, in the style of "Red Family (Ruby Red)". */
export const TONE_LABELS: Record<LightBand, Record<ChromaBand, string>> = {
  'very dark': {
    grayish: 'Charcoal',
    muted: 'Shadowed',
    moderate: 'Deep Night',
    strong: 'Deep Jewel',
    vivid: 'Dark Jewel',
  },
  dark: {
    grayish: 'Smoky Dark',
    muted: 'Deep Muted',
    moderate: 'Deep',
    strong: 'Rich Deep',
    vivid: 'Deep Vivid',
  },
  medium: {
    grayish: 'Grayed',
    muted: 'Dusty',
    moderate: 'Classic',
    strong: 'Rich',
    vivid: 'Vivid',
  },
  light: {
    grayish: 'Misty',
    muted: 'Soft Muted',
    moderate: 'Soft',
    strong: 'Bright',
    vivid: 'Bright Vivid',
  },
  pale: {
    grayish: 'Pale Gray',
    muted: 'Dusty Pastel',
    moderate: 'Pastel',
    strong: 'Bright Pastel',
    vivid: 'Luminous Pastel',
  },
};

export const DESCRIPTION_TEMPLATES = [
  '{name} is a {adj}, {chroma} {noun}{undertone}, reminiscent of {imagery}. {note}',
  '{name} is a {adj}, {chroma} {noun}{undertone} that recalls {imagery}. {note}',
  'A {chroma} {noun} in a {adj} register{undertone}, {name} looks like {imagery}. {note}',
  'This {adj} {noun} has a {chroma} character{undertone}; {name} brings to mind {imagery}. {note}',
  '{name} is a {adj} shade of {noun}{undertone} whose {chroma} tone evokes {imagery}. {note}',
];

export const SYMBOLISM_TEMPLATES = [
  '{name} symbolizes {sym1}, as well as {sym2}; its {band} tone adds a note of {bandSym}.',
  '{name} evokes {sym1}, and its {band} quality also suggests {bandSym}.',
  'Associated with {sym1} and with {sym2}, {name} carries a sense of {bandSym}.',
  '{name} represents {sym1}, shaded by {bandSym}.',
  'In {name}, {sym1} meets {bandSym}.',
];

export const USE_TEMPLATES = [
  'Well suited to {use1}, {use2}, and {use3}. {pairing}',
  'Ideal for {use1} and {use2}, and effective in {use3}. {pairing}',
  'Works well in {use1}, {use2}, or {use3}. {pairing}',
  'A strong choice for {use1}, {use2}, and {use3}. {pairing}',
  'Use it for {use1} and {use2}; it also suits {use3}. {pairing}',
];

export const PAIRING_TEMPLATES = [
  'Pairs well with {complement} accents for contrast.',
  'For contrast, combine it with {complement}.',
  'Its natural complement is {complement}.',
  'Balance it with {neutral} neutrals or a touch of {complement}.',
  'Try it alongside {neutral} tones, with {complement} as an accent.',
];
