import type { HarmonyDef, ThemeDef, CBType, GradientPreset } from "@/types";
import { hexToRgb } from "@/lib/utils/colorMath";
import ColorNames from "./named-colors/color-names.json";

// ─── Harmonies ────────────────────────────────────────────────────────────────

export const HARMONIES: HarmonyDef[] = [
  {
    id: "analogous",
    label: "Analogous",
    desc: "Adjacent hues — harmonious and serene. (Matsuda V template)",
  },
  {
    id: "complementary",
    label: "Complementary",
    desc: "Colors opposite on the wheel — high contrast.",
  },
  {
    id: "split-comp",
    label: "Split-Comp",
    desc: "A base plus two adjacent to its complement.",
  },
  {
    id: "triadic",
    label: "Triadic",
    desc: "Three evenly-spaced hues — vibrant and diverse.",
  },
  {
    id: "tetradic",
    label: "Tetradic",
    desc: "Four hues in two complementary pairs.",
  },
  { id: "square", label: "Square", desc: "Four hues equally spaced at 90°." },
  {
    id: "monochromatic",
    label: "Monochromatic",
    desc: "One hue, varying saturation and lightness.",
  },
  {
    id: "shades",
    label: "Shades & Tints",
    desc: "Deep shadow to bright highlight on one hue.",
  },
  {
    id: "double-split",
    label: "Double Split",
    desc: "Two split-complementary pairs — complex.",
  },
  {
    id: "compound",
    label: "Compound",
    desc: "Near-complementary — sophisticated, nuanced.",
  },
  {
    id: "natural",
    label: "Natural",
    desc: "Muted, organic, naturalistic tones.",
  },
  {
    id: "random",
    label: "Random",
    desc: "Golden-ratio hue stepping — always harmonious.",
  },
  {
    id: "matsuda_L",
    label: "Matsuda L",
    desc: "Large cluster + small accent at 90° — elegant asymmetry.",
  },
  {
    id: "matsuda_Y",
    label: "Matsuda Y",
    desc: "Wide cluster with a single complement accent.",
  },
  {
    id: "matsuda_X",
    label: "Matsuda X",
    desc: "Two opposite clusters — bold complementary spread.",
  },
  {
    id: "matsuda_T",
    label: "Matsuda T",
    desc: "Half-wheel dominance — warm or cool palette.",
  },
];

// ─── Themes ───────────────────────────────────────────────────────────────────

export const THEMES: ThemeDef[] = [
  {
    name: "Forest",
    mode: "analogous",
    seeds: ["#2D5016", "#5C8A3C", "#8FBC5A", "#C8E6A0", "#3D7A4A"],
  },
  {
    name: "Sunset",
    mode: "analogous",
    seeds: ["#FF6B35", "#F7C59F", "#FF4D6D", "#C9184A", "#FFBA08"],
  },
  {
    name: "Ocean Wave",
    mode: "analogous",
    seeds: ["#0077B6", "#00B4D8", "#90E0EF", "#CAF0F8", "#48CAE4"],
  },
  {
    name: "Blue Lagoon",
    mode: "complementary",
    seeds: ["#006994", "#0099CC", "#66CCDD", "#FFDD99", "#FF9944"],
  },
  {
    name: "Mystic Night",
    mode: "analogous",
    seeds: ["#10002B", "#240046", "#3C096C", "#7B2FBE", "#E0AAFF"],
  },
  {
    name: "Rose Garden",
    mode: "analogous",
    seeds: ["#FF006E", "#FB5607", "#FFBE0B", "#FF4D6D", "#C9184A"],
  },
  {
    name: "Desert Sand",
    mode: "analogous",
    seeds: ["#C67B3B", "#DDA15E", "#BC6C25", "#FEFAE0", "#606C38"],
  },
  {
    name: "Aurora",
    mode: "analogous",
    seeds: ["#6A0572", "#AB83A1", "#00F5D4", "#00BBF9", "#F15BB5"],
  },
  {
    name: "Harvest",
    mode: "analogous",
    seeds: ["#D62828", "#F77F00", "#FCBF49", "#EAE2B7", "#003049"],
  },
  {
    name: "Crashing Wave",
    mode: "split-comp",
    seeds: ["#023E8A", "#0077B6", "#48CAE4", "#ADE8F4", "#90E0EF"],
  },
  {
    name: "Wildflower",
    mode: "triadic",
    seeds: ["#E040FB", "#00E676", "#FFEB3B", "#FF4081", "#40C4FF"],
  },
  { name: "Stormy", mode: "monochromatic", seeds: ["#37474F"] },
  {
    name: "Cherry Blossom",
    mode: "analogous",
    seeds: ["#FF85A1", "#FFB3C6", "#FF4D6D", "#FFC2D4", "#FFCCD5"],
  },
  {
    name: "Cyber",
    mode: "complementary",
    seeds: ["#00F5D4", "#F72585", "#7209B7", "#3A0CA3", "#4CC9F0"],
  },
  {
    name: "Earth",
    mode: "analogous",
    seeds: ["#8B4513", "#A0522D", "#6B4226", "#DEB887", "#C8A47E"],
  },
  {
    name: "Lagoon",
    mode: "analogous",
    seeds: ["#006D5B", "#40826D", "#ACE1AF", "#20B2AA", "#48D1CC"],
  },
];

// ─── Color Blindness Types ───────────────────────────────────────────────────

export const CB_TYPES: CBType[] = [
  {
    id: "normal",
    name: "Normal Vision",
    desc: "Full color perception",
    matrix: [1, 0, 0, 0, 1, 0, 0, 0, 1],
  },
  {
    id: "deuteranopia",
    name: "Deuteranopia",
    desc: "Green-blind · ~6% of males",
    matrix: [0.367, 0.861, -0.228, 0.28, 0.673, 0.047, -0.012, 0.043, 0.969],
  },
  {
    id: "protanopia",
    name: "Protanopia",
    desc: "Red-blind · ~2% of males",
    matrix: [0.152, 1.053, -0.205, 0.115, 0.786, 0.099, -0.004, -0.048, 1.052],
  },
  {
    id: "tritanopia",
    name: "Tritanopia",
    desc: "Blue-yellow blind · ~0.01%",
    matrix: [1.256, -0.077, -0.179, -0.079, 0.931, 0.148, 0.005, 0.691, 0.304],
  },
  {
    id: "achromatopsia",
    name: "Achromatopsia",
    desc: "Complete color blindness · very rare",
    matrix: [0.299, 0.587, 0.114, 0.299, 0.587, 0.114, 0.299, 0.587, 0.114],
  },
  {
    id: "deuteranomaly",
    name: "Deuteranomaly",
    desc: "Reduced green sensitivity · ~5% of males",
    matrix: [0.531, 0.566, -0.097, 0.176, 0.764, 0.06, -0.004, 0.04, 0.964],
  },
];

// ─── Gradient Presets ─────────────────────────────────────────────────────────

export const GRAD_PRESETS: GradientPreset[] = [
  {
    name: "Ocean Breeze",
    type: "linear",
    dir: "to right",
    stops: [
      { hex: "#0077b6", pos: 0 },
      { hex: "#00b4d8", pos: 50 },
      { hex: "#90e0ef", pos: 100 },
    ],
  },
  {
    name: "Sunset Glow",
    type: "linear",
    dir: "to bottom right",
    stops: [
      { hex: "#ff4d6d", pos: 0 },
      { hex: "#ff9f1c", pos: 50 },
      { hex: "#ffbf69", pos: 100 },
    ],
  },
  {
    name: "Midnight",
    type: "linear",
    dir: "to bottom",
    stops: [
      { hex: "#10002b", pos: 0 },
      { hex: "#3c096c", pos: 50 },
      { hex: "#7b2fbe", pos: 100 },
    ],
  },
  {
    name: "Aurora",
    type: "linear",
    dir: "to right",
    stops: [
      { hex: "#00f5d4", pos: 0 },
      { hex: "#00bbf9", pos: 50 },
      { hex: "#f15bb5", pos: 100 },
    ],
  },
  {
    name: "Forest",
    type: "linear",
    dir: "135deg",
    stops: [
      { hex: "#2d5016", pos: 0 },
      { hex: "#5c8a3c", pos: 50 },
      { hex: "#c8e6a0", pos: 100 },
    ],
  },
  {
    name: "Rose Gold",
    type: "radial",
    dir: "",
    stops: [
      { hex: "#b76e79", pos: 0 },
      { hex: "#fad6a5", pos: 100 },
    ],
  },
  {
    name: "Cyber",
    type: "conic",
    dir: "from 0deg",
    stops: [
      { hex: "#7209b7", pos: 0 },
      { hex: "#f72585", pos: 50 },
      { hex: "#00f5d4", pos: 100 },
    ],
  },
];

// ─── Color Names — pre-parsed at module load ──────────────────────────────────

const NAMED_RAW: [string, string][] = ColorNames.map((color) => [
  color.name,
  color.hex,
]);
/* OLD NAMES
[
  ["Crimson", "#DC143C"],
  ["Firebrick", "#B22222"],
  ["Scarlet", "#FF2400"],
  ["Tomato", "#FF6347"],
  ["Coral", "#FF7F50"],
  ["Indian Red", "#CD5C5C"],
  ["Carmine", "#960018"],
  ["Ruby", "#9B111E"],
  ["Raspberry", "#872657"],
  ["Rose", "#FF007F"],
  ["Hot Pink", "#FF69B4"],
  ["Deep Pink", "#FF1493"],
  ["Flamingo", "#FC8EAC"],
  ["Blush", "#DE5D83"],
  ["Cerise", "#DE3163"],
  ["Amaranth", "#E52B50"],
  ["Orange", "#FF8C00"],
  ["Tangerine", "#F28500"],
  ["Amber", "#FFBF00"],
  ["Pumpkin", "#FF7518"],
  ["Burnt Orange", "#CC5500"],
  ["Terracotta", "#C26A49"],
  ["Sienna", "#A0522D"],
  ["Peru", "#CD853F"],
  ["Copper", "#B87333"],
  ["Ochre", "#CC7722"],
  ["Saffron", "#F4C430"],
  ["Apricot", "#FBCEB1"],
  ["Peach", "#FFCBA4"],
  ["Salmon", "#FA8072"],
  ["Yellow", "#FFE600"],
  ["Gold", "#FFD700"],
  ["Goldenrod", "#DAA520"],
  ["Lemon", "#FFF44F"],
  ["Corn", "#FBEC5D"],
  ["Khaki", "#C3B091"],
  ["Sand", "#C2B280"],
  ["Cream", "#FFFDD0"],
  ["Ivory", "#FFFFF0"],
  ["Beige", "#F5F5DC"],
  ["Wheat", "#F5DEB3"],
  ["Green", "#008000"],
  ["Lime", "#00FF00"],
  ["Forest Green", "#228B22"],
  ["Emerald", "#50C878"],
  ["Jade", "#00A86B"],
  ["Mint", "#98FF98"],
  ["Sage", "#8FAE8B"],
  ["Fern", "#4F7942"],
  ["Moss", "#8A9A5B"],
  ["Olive", "#808000"],
  ["Avocado", "#568203"],
  ["Chartreuse", "#7FFF00"],
  ["Spring Green", "#00FF7F"],
  ["Sea Green", "#2E8B57"],
  ["Aquamarine", "#7FFFD4"],
  ["Tea Green", "#D0F0C0"],
  ["Hunter Green", "#355E3B"],
  ["Pine", "#01796F"],
  ["Viridian", "#40826D"],
  ["Teal", "#008080"],
  ["Cyan", "#00FFFF"],
  ["Turquoise", "#40E0D0"],
  ["Dark Turquoise", "#00CED1"],
  ["Cadet Blue", "#5F9EA0"],
  ["Cerulean", "#007BA7"],
  ["Sky Blue", "#87CEEB"],
  ["Verdigris", "#43B3AE"],
  ["Blue", "#0000FF"],
  ["Navy", "#001F5B"],
  ["Royal Blue", "#4169E1"],
  ["Cobalt", "#0047AB"],
  ["Sapphire", "#0F52BA"],
  ["Cornflower Blue", "#6495ED"],
  ["Dodger Blue", "#1E90FF"],
  ["Steel Blue", "#4682B4"],
  ["Slate Blue", "#6A5ACD"],
  ["Denim", "#1560BD"],
  ["Iris", "#5A4FCF"],
  ["Periwinkle", "#CCCCFF"],
  ["Azure", "#007FFF"],
  ["Baby Blue", "#89CFF0"],
  ["Midnight Blue", "#191970"],
  ["Purple", "#800080"],
  ["Violet", "#EE82EE"],
  ["Indigo", "#4B0082"],
  ["Lavender", "#E6E6FA"],
  ["Mauve", "#E0B0FF"],
  ["Plum", "#DDA0DD"],
  ["Orchid", "#DA70D6"],
  ["Fuchsia", "#FF00FF"],
  ["Wisteria", "#C9A0DC"],
  ["Lilac", "#C8A2C8"],
  ["Heliotrope", "#DF73FF"],
  ["Thistle", "#D8BFD8"],
  ["Medium Purple", "#9370DB"],
  ["Rebecca Purple", "#663399"],
  ["Amethyst", "#9966CC"],
  ["Grape", "#6F2DA8"],
  ["Eggplant", "#614051"],
  ["Pink", "#FFC0CB"],
  ["Carnation", "#FFA6C9"],
  ["Bubblegum", "#FE5BAC"],
  ["Watermelon", "#FC6C85"],
  ["Brown", "#8B4513"],
  ["Chocolate", "#D2691E"],
  ["Caramel", "#C68642"],
  ["Tan", "#D2B48C"],
  ["Mocha", "#8B5A2B"],
  ["Coffee", "#6F4E37"],
  ["Espresso", "#4C2C2A"],
  ["Sepia", "#704214"],
  ["Walnut", "#5C3317"],
  ["Chestnut", "#954535"],
  ["Mahogany", "#C04000"],
  ["Rust", "#B7410E"],
  ["Burnt Sienna", "#E97451"],
  ["White", "#FFFFFF"],
  ["Snow", "#FFFAFA"],
  ["Seashell", "#FFF5EE"],
  ["Antique White", "#FAEBD7"],
  ["Light Gray", "#D3D3D3"],
  ["Silver", "#C0C0C0"],
  ["Gray", "#808080"],
  ["Slate Gray", "#708090"],
  ["Dim Gray", "#696969"],
  ["Charcoal", "#36454F"],
  ["Ash", "#B2BEB5"],
  ["Graphite", "#474A51"],
  ["Jet", "#343434"],
  ["Black", "#000000"],
  ["Rose Gold", "#B76E79"],
  ["Champagne", "#FAD6A5"],
  ["Bronze", "#CD7F32"],
  ["Brass", "#B5A642"],
  ["Gunmetal", "#2A3439"],
  ["Celadon", "#ACE1AF"],
  ["Vermilion", "#E34234"],
];
*/

export const NAMED = NAMED_RAW.map(([name, hex]) => ({
  name,
  hex: hex.toLowerCase(),
  rgb: hexToRgb(hex),
}));
